name: Update Leaderboard

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches: [main]

env:
  COMPETITION_START: "2024-12-18"
  COMPETITION_END: "2025-01-18"
  API_URL: "https://api.torn.com/v2/faction/contributors?stat=gymenergy&cat=current&comment=Olu"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Debug environment
        run: |
          echo "=== Environment Debug ==="
          echo "Working directory: $(pwd)"
          echo "Listing files:"
          ls -la
          echo "Git status:"
          git status
          echo ""
      
      - name: Update leaderboard
        env:
          API_KEY: ${{ secrets.TORN_API_KEY }}
          COMP_START: ${{ env.COMPETITION_START }}
          COMP_END: ${{ env.COMPETITION_END }}
          API_URL: ${{ env.API_URL }}
        run: |
          set -e
          
          echo "================================================"
          echo "LEADERBOARD UPDATE STARTING"
          echo "================================================"
          echo "Competition: $COMP_START to $COMP_END"
          echo "Time: $(date -u)"
          echo "Directory: $(pwd)"
          echo ""
          
          # ============================================
          # STEP 1: VALIDATE ENVIRONMENT
          # ============================================
          echo ">>> STEP 1: Validating environment"
          
          if [ -z "$API_KEY" ]; then
            echo "❌ ERROR: TORN_API_KEY not set"
            exit 1
          fi
          echo "✓ API key found"
          
          # Test write permissions
          touch test_write.tmp && rm test_write.tmp || {
            echo "❌ ERROR: Cannot write to directory"
            exit 1
          }
          echo "✓ Write permissions OK"
          
          TODAY=$(date +%Y-%m-%d)
          if [[ "$TODAY" > "$COMP_END" ]]; then
            SKIP_FETCH=true
            STATUS="🏁 Competition Ended"
            STATUS_COLOR="rgba(255,71,87,0.8)"
          else
            SKIP_FETCH=false
            STATUS="🔥 Competition Active"
            STATUS_COLOR="rgba(39,174,96,0.8)"
          fi
          echo "✓ Status: $STATUS"
          echo ""
          
          # ============================================
          # STEP 2: FETCH CURRENT DATA
          # ============================================
          echo ">>> STEP 2: Fetching current data"
          
          if [ "$SKIP_FETCH" = false ]; then
            echo "Calling API: ${API_URL:0:50}..."
            
            HTTP_CODE=$(curl -s -w "%{http_code}" -o current.json "${API_URL}&key=${API_KEY}")
            
            if [ "$HTTP_CODE" != "200" ]; then
              echo "❌ ERROR: API returned HTTP $HTTP_CODE"
              [ -f current.json ] && cat current.json
              exit 1
            fi
            echo "✓ HTTP $HTTP_CODE - Success"
            
            if [ ! -f current.json ]; then
              echo "❌ ERROR: current.json not created"
              exit 1
            fi
            echo "✓ current.json created ($(wc -c < current.json) bytes)"
            
            if ! jq -e '.contributors' current.json >/dev/null 2>&1; then
              echo "❌ ERROR: Invalid JSON structure"
              head -n 20 current.json
              exit 1
            fi
            
            CONTRIB_COUNT=$(jq '.contributors | length' current.json)
            echo "✓ Valid JSON with $CONTRIB_COUNT contributors"
          else
            if [ ! -f current.json ]; then
              echo "❌ ERROR: Competition ended but current.json missing"
              exit 1
            fi
            echo "✓ Using existing current.json"
          fi
          echo ""
          
          # ============================================
          # STEP 3: BASELINE MANAGEMENT
          # ============================================
          echo ">>> STEP 3: Managing baseline"
          
          if [ ! -f baseline.json ]; then
            echo "No baseline found - creating from current data"
            
            cp current.json baseline.json
            
            if [ ! -f baseline.json ]; then
              echo "❌ ERROR: Failed to create baseline.json"
              exit 1
            fi
            echo "✓ baseline.json created ($(wc -c < baseline.json) bytes)"
            
            echo "Baseline snapshot:"
            jq -r '.contributors | sort_by(-.value) | .[:3][] | "  \(.username): \(.value)"' baseline.json
          else
            echo "✓ baseline.json exists ($(wc -c < baseline.json) bytes)"
          fi
          echo ""
          
          # ============================================
          # STEP 4: CALCULATE PROGRESS
          # ============================================
          echo ">>> STEP 4: Calculating progress"
          
          jq -n '
            # Load data
            ($baseline[0].contributors | INDEX(.id | tostring)) as $base |
            ($current[0].contributors) as $curr |
            
            # Calculate progress for each person
            [
              $curr[] | 
              . as $person |
              ($base[$person.id | tostring] // {value: 0}) as $baseData |
              {
                id: $person.id,
                username: $person.username,
                baseline: $baseData.value,
                current: $person.value,
                progress: ($person.value - $baseData.value),
                in_faction: $person.in_faction
              }
            ] | sort_by(-.progress)
          ' \
            --slurpfile baseline baseline.json \
            --slurpfile current current.json > progress.json
          
          if [ ! -f progress.json ]; then
            echo "❌ ERROR: progress.json not created"
            exit 1
          fi
          echo "✓ progress.json created ($(wc -c < progress.json) bytes)"
          
          if ! jq empty progress.json 2>/dev/null; then
            echo "❌ ERROR: progress.json contains invalid JSON"
            cat progress.json
            exit 1
          fi
          
          TOTAL=$(jq 'length' progress.json)
          ACTIVE=$(jq '[.[] | select(.progress > 0)] | length' progress.json)
          echo "✓ Processed $TOTAL users ($ACTIVE with progress)"
          
          echo "Top 3 progress:"
          jq -r '.[:3][] | "  \(.username): +\(.progress) (baseline: \(.baseline), current: \(.current))"' progress.json
          echo ""
          
          # ============================================
          # STEP 5: BUILD HTML PAGE
          # ============================================
          echo ">>> STEP 5: Building HTML page"
          
          # Start HTML file
          cat > index.html << 'HTMLSTART'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Gym Energy Leaderboard</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      padding: 20px;
    }
    .container { max-width: 1000px; margin: 0 auto; }
    .header { text-align: center; color: white; margin-bottom: 30px; }
    .header h1 { font-size: 2.5em; margin-bottom: 10px; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); }
    .status {
      padding: 10px 20px;
      border-radius: 20px;
      display: inline-block;
      margin-top: 10px;
      font-weight: bold;
      box-shadow: 0 4px 6px rgba(0,0,0,0.2);
    }
    .dates { color: rgba(255,255,255,0.9); margin-top: 10px; font-size: 0.9em; }
    .podium {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 20px;
      margin-bottom: 30px;
    }
    .podium-card {
      background: white;
      border-radius: 15px;
      padding: 25px;
      text-align: center;
      box-shadow: 0 10px 30px rgba(0,0,0,0.2);
      transition: transform 0.3s;
    }
    .podium-card:hover { transform: translateY(-5px); }
    .podium-card:first-child { background: linear-gradient(135deg, #f6d365 0%, #fda085 100%); }
    .medal { font-size: 3em; margin-bottom: 10px; }
    .username { font-size: 1.4em; font-weight: bold; margin-bottom: 5px; }
    .progress { font-size: 1.8em; color: #667eea; font-weight: bold; margin-top: 5px; }
    .podium-card:first-child .progress { color: #fff; }
    .baseline-info { font-size: 0.85em; color: #666; margin-top: 5px; }
    .podium-card:first-child .baseline-info { color: rgba(255,255,255,0.8); }
    .table-box {
      background: white;
      border-radius: 15px;
      padding: 20px;
      box-shadow: 0 10px 30px rgba(0,0,0,0.2);
      overflow-x: auto;
    }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 15px 12px; text-align: left; border-bottom: 1px solid #eee; }
    th { background: #f8f9fa; font-weight: bold; color: #667eea; position: sticky; top: 0; }
    tr:hover { background: #f8f9fa; }
    .rank-cell { width: 80px; text-align: center; font-weight: bold; font-size: 1.1em; }
    .num-cell { text-align: right; font-weight: bold; }
    .prog-cell { color: #27ae60; }
    .base-cell { color: #95a5a6; font-size: 0.9em; }
    .zero-row { opacity: 0.5; }
    .footer {
      text-align: center;
      color: white;
      margin-top: 20px;
      font-size: 0.9em;
      background: rgba(0,0,0,0.2);
      padding: 15px;
      border-radius: 10px;
    }
    @media (max-width: 768px) {
      .header h1 { font-size: 1.8em; }
      .podium { grid-template-columns: 1fr; }
      th, td { padding: 10px 8px; font-size: 0.9em; }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🏋️ Gym Energy Competition</h1>
      <p>Tracking progress from competition start</p>
HTMLSTART
          
          # Add status badge
          cat >> index.html << STATUSBLOCK
      <div class="status" style="background: ${STATUS_COLOR};">${STATUS}</div>
      <div class="dates">${COMP_START} to ${COMP_END}</div>
    </div>
    
    <div class="podium">
STATUSBLOCK
          
          # Build podium (top 3)
          MEDALS=("🥇" "🥈" "🥉")
          PODIUM_COUNT=0
          
          jq -r '.[:3][] | @json' progress.json | while IFS= read -r row; do
            PROG=$(echo "$row" | jq -r '.progress')
            [ "$PROG" -le 0 ] && break
            
            USER=$(echo "$row" | jq -r '.username')
            BASE=$(echo "$row" | jq -r '.baseline')
            
            # Format numbers
            PROG_FMT=$(printf "%'d" $PROG 2>/dev/null || echo "$PROG")
            BASE_FMT=$(printf "%'d" $BASE 2>/dev/null || echo "$BASE")
            
            cat >> index.html << PODIUMCARD
      <div class="podium-card">
        <div class="medal">${MEDALS[$PODIUM_COUNT]}</div>
        <div class="username">${USER}</div>
        <div class="progress">+${PROG_FMT}</div>
        <div class="baseline-info">Started at: ${BASE_FMT}</div>
      </div>
PODIUMCARD
            
            PODIUM_COUNT=$((PODIUM_COUNT + 1))
          done
          
          # If no progress, show placeholder
          if [ $PODIUM_COUNT -eq 0 ]; then
            cat >> index.html << 'NODATA'
      <div class="podium-card">
        <div class="username">No progress yet</div>
        <div class="baseline-info">Competition just started!</div>
      </div>
NODATA
          fi
          
          # Start table
          cat >> index.html << 'TABLESTART'
    </div>
    
    <div class="table-box">
      <table>
        <thead>
          <tr>
            <th class="rank-cell">Rank</th>
            <th>Username</th>
            <th class="num-cell">Progress</th>
            <th class="num-cell">Baseline</th>
            <th class="num-cell">Current</th>
          </tr>
        </thead>
        <tbody>
TABLESTART
          
          # Build table rows
          RANK=1
          jq -r '.[] | @json' progress.json | while IFS= read -r row; do
            USER=$(echo "$row" | jq -r '.username')
            PROG=$(echo "$row" | jq -r '.progress')
            BASE=$(echo "$row" | jq -r '.baseline')
            CURR=$(echo "$row" | jq -r '.current')
            
            [ -z "$USER" ] || [ "$USER" = "null" ] && continue
            
            PROG_FMT=$(printf "%'d" $PROG 2>/dev/null || echo "$PROG")
            BASE_FMT=$(printf "%'d" $BASE 2>/dev/null || echo "$BASE")
            CURR_FMT=$(printf "%'d" $CURR 2>/dev/null || echo "$CURR")
            
            if [ "$PROG" -eq 0 ]; then
              ROW_CLASS="zero-row"
            else
              ROW_CLASS=""
            fi
            
            cat >> index.html << TABLEROW
          <tr class="${ROW_CLASS}">
            <td class="rank-cell">${RANK}</td>
            <td>${USER}</td>
            <td class="num-cell prog-cell">+${PROG_FMT}</td>
            <td class="num-cell base-cell">${BASE_FMT}</td>
            <td class="num-cell">${CURR_FMT}</td>
          </tr>
TABLEROW
            
            RANK=$((RANK + 1))
          done
          
          # Finish HTML
          TIMESTAMP=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          NEXT=$(date -u -d "+6 hours" "+%Y-%m-%d %H:%M UTC" 2>/dev/null || echo "In 6 hours")
          
          cat >> index.html << HTMLEND
        </tbody>
      </table>
    </div>
    
    <div class="footer">
      <strong>Last updated:</strong> ${TIMESTAMP}<br>
      <strong>Next update:</strong> ${NEXT}
    </div>
  </div>
</body>
</html>
HTMLEND
          
          if [ ! -f index.html ]; then
            echo "❌ ERROR: index.html not created"
            exit 1
          fi
          echo "✓ index.html created ($(wc -c < index.html) bytes)"
          echo ""
          
          # ============================================
          # STEP 6: COMMIT AND PUSH
          # ============================================
          echo ">>> STEP 6: Committing changes"
          
          echo "Files to commit:"
          ls -lh baseline.json current.json progress.json index.html
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add -f baseline.json current.json progress.json index.html
          
          echo "Git status:"
          git status --short
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update leaderboard - $(date -u '+%Y-%m-%d %H:%M UTC')"
            
            echo "Pushing to GitHub..."
            MAX_RETRIES=3
            RETRY=0
            
            until git push || [ $RETRY -eq $MAX_RETRIES ]; do
              RETRY=$((RETRY + 1))
              echo "Push failed, retry $RETRY/$MAX_RETRIES..."
              sleep 3
              git pull --rebase origin main
            done
            
            if [ $RETRY -eq $MAX_RETRIES ]; then
              echo "❌ ERROR: Failed to push after $MAX_RETRIES attempts"
              exit 1
            fi
            
            echo "✓ Changes pushed successfully"
          fi
          
          echo ""
          echo "================================================"
          echo "✅ LEADERBOARD UPDATE COMPLETE"
          echo "================================================"
